# Generated by Django 6.0.6 on 2026-08-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='parameter_a',
        ),
        migrations.RemoveField(
            model_name='score',
            name='parameter_b',
        ),
        migrations.RemoveField(
            model_name='score',
            name='parameter_c',
        ),
        migrations.AddField(
            model_name='score',
            name='additional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='puzzle_pk',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
