# Generated by Django 6.0.6 on 2026-08-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_remove_score_parameter_a_remove_score_parameter_b_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['competition', 'puzzle_pk', '-adjusted_score']},
        ),
    ]
