# Generated by Django 6.0.6 on 2026-08-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_display_name'),
        ('scores', '0003_alter_score_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('competition', 'puzzle_pk', 'player'), name='unique_competition_puzzle_pk_player'),
        ),
    ]
