# Generated by Django 6.0.6 on 2026-08-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_score_unique_competition_puzzle_pk_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['name']},
        ),
    ]
