# Generated by Django 6.0.6 on 2026-06-15 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('publication_datetime', models.DateTimeField(blank=True, null=True)),
                ('num_rows', models.PositiveIntegerField()),
                ('num_cols', models.PositiveIntegerField()),
                ('blocked_out_squares', models.JSONField(default=list)),
                ('cells', models.JSONField(default=list)),
                ('new_york_times_rules', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]+$', 'Text must be uppercase A-Z only.')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='crossword.word')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('direction', models.CharField(choices=[('A', 'Across'), ('D', 'Down')], max_length=1)),
                ('clue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='crossword.clue')),
                ('crossword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='crossword.crossword')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='crossword.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('crossword', 'number', 'direction'), name='unique_crossword_number_direction')],
            },
        ),
        migrations.AddConstraint(
            model_name='clue',
            constraint=models.UniqueConstraint(fields=('text', 'clue'), name='unique_text_clue'),
        ),
    ]
