# Generated by Django 6.0.6 on 2026-06-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0002_rename_new_york_times_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossword',
            options={'permissions': [('can_generate_crosswords', 'Can generate crosswords')]},
        ),
    ]
