# Generated by Django 6.0.6 on 2026-06-23 12:58

import crossword.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0005_rename_publication_datetime_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='authors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='crossword',
            name='copyright',
            field=models.CharField(default=crossword.models.default_copyright, max_length=200),
        ),
        migrations.AddField(
            model_name='crossword',
            name='editors',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
