# Generated by Django 6.0.6 on 2026-07-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0007_load_crosswords'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source_crossword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_words', to='crossword.crossword'),
        ),
    ]
