# Generated by Django 6.0.6 on 2026-07-01 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0008_add_source_crossword_to_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='source_crossword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_clues', to='crossword.crossword'),
        ),
    ]
