# Generated by Django 6.0.6 on 2026-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0009_add_source_crossword_to_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='exclude_from_recommendations',
            field=models.BooleanField(default=False),
        ),
    ]
