# Generated by Django 6.0.6 on 2026-07-26 06:55

import crossword.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0011_crossword_owner_crossword_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='private_link',
            field=models.CharField(default=crossword.models.random_string, max_length=60),
        ),
    ]
