# Generated by Django 6.0.6 on 2026-07-26 07:40

import crossword.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0013_fix_duplicate_private_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossword',
            name='private_link',
            field=models.CharField(default=crossword.models.random_string, max_length=60, unique=True),
        ),
    ]
