# Generated by Django 6.0.6 on 2026-08-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0014_alter_crossword_private_link'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.competition'),
        ),
    ]
