# Generated by Django 6.1.1 on 2026-09-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0015_crossword_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
