# Generated by Django 6.0.6 on 2026-09-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0016_crossword_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='display_slot_length',
            field=models.BooleanField(default=True),
        ),
    ]
