# Generated by Django 5.2.13 on 2026-09-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.CharField(max_length=81, unique=True)),
                ('solution', models.CharField(blank=True, max_length=81)),
                ('number', models.IntegerField(null=True)),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='publish time')),
                ('difficulty', models.CharField(choices=[('0', 'Unknown'), ('1', 'Very easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very hard'), ('6', 'Extremely hard')], default='0', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
