# Generated by Django 6.0.6 on 2026-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('correct', True)), fields=('question',), name='one_correct_answer_per_question'),
        ),
    ]
