# Generated by Django 6.0.6 on 2026-08-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_answer_one_correct_answer_per_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'permissions': [('can_generate_quizzes', 'Can generate quizzes')]},
        ),
    ]
