# Generated by Django 6.1.1 on 2026-10-01 10:41

import crossword.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('editors', models.CharField(blank=True, max_length=200)),
                ('copyright', models.CharField(default=crossword.models.default_copyright, max_length=200)),
                ('groups', models.JSONField(blank=True, default=list)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GroupUp',
                'permissions': [('can_generate_groupups', 'Can generate GroupUps')],
            },
        ),
    ]
